In [1]:
import numpy as np

# Columns: [Math, Science, English, History, Computer Science]
student_marks = np.array([
    [85, 78, 92, 74, 88],  # Student 1
    [76, 85, 89, 80, 90],  # Student 2
    [90, 88, 94, 86, 91],  # Student 3
    [65, 70, 72, 68, 75],  # Student 4
    [88, 92, 85, 90, 94],  # Student 5
    [70, 68, 75, 72, 78],  # Student 6
    [95, 94, 96, 92, 98],  # Student 7
    [82, 80, 78, 85, 84],  # Student 8
    [60, 65, 70, 62, 68],  # Student 9
    [78, 75, 80, 77, 82]   # Student 10
])

student_names = np.array([
    "Alice", "Bob", "Charlie", "David", "Eva",
    "Frank", "Grace", "Hannah", "Ian", "Jack"
])

print("Student Marks Array:\n", student_marks)


Student Marks Array:
 [[85 78 92 74 88]
 [76 85 89 80 90]
 [90 88 94 86 91]
 [65 70 72 68 75]
 [88 92 85 90 94]
 [70 68 75 72 78]
 [95 94 96 92 98]
 [82 80 78 85 84]
 [60 65 70 62 68]
 [78 75 80 77 82]]


In [2]:
# Function to calculate percentage for each student.
def cal_percentage(scores):
    total = np.sum(scores)
    percentage = (total / 500) * 100
    return percentage

print("Student Scores and Percentages:")
for i, student in enumerate(student_marks):
    print(f"Student {i+1} Scores: {student}, Percentage: {cal_percentage(student):.2f}%")

Student Scores and Percentages:
Student 1 Scores: [85 78 92 74 88], Percentage: 83.40%
Student 2 Scores: [76 85 89 80 90], Percentage: 84.00%
Student 3 Scores: [90 88 94 86 91], Percentage: 89.80%
Student 4 Scores: [65 70 72 68 75], Percentage: 70.00%
Student 5 Scores: [88 92 85 90 94], Percentage: 89.80%
Student 6 Scores: [70 68 75 72 78], Percentage: 72.60%
Student 7 Scores: [95 94 96 92 98], Percentage: 95.00%
Student 8 Scores: [82 80 78 85 84], Percentage: 81.80%
Student 9 Scores: [60 65 70 62 68], Percentage: 65.00%
Student 10 Scores: [78 75 80 77 82], Percentage: 78.40%


In [3]:
# Function to calculate average marks for each subject.
def cal_average(marks):
    return np.mean(marks, axis=0)

average_marks = cal_average(student_marks)
print("\nAverage Marks for Each Subject:")
subjects = ["Math", "Science", "English", "History", "Computer Science"]

for subject, avg in zip(subjects, average_marks):
    print(f"{subject}: {avg:.2f}")


Average Marks for Each Subject:
Math: 78.90
Science: 79.50
English: 83.10
History: 78.60
Computer Science: 84.80


In [4]:
#Function to calculate Highest and lowest marks for each subject.
def cal_high_low(marks):
    highest = np.max(marks, axis =0)
    lowest = np.min(marks, axis =0)
    return highest, lowest

highest_marks, lowest_marks = cal_high_low(student_marks)
print("\nHighest and Lowest Marks for Each Subject:")

for subject , high, low in zip(subjects, highest_marks, lowest_marks):
    print(f"{subject}: Highest: {high}, Lowest: {low}")


Highest and Lowest Marks for Each Subject:
Math: Highest: 95, Lowest: 60
Science: Highest: 94, Lowest: 65
English: Highest: 96, Lowest: 70
History: Highest: 92, Lowest: 62
Computer Science: Highest: 98, Lowest: 68


In [5]:
#Function to find the topper in the class based on total marks.
def find_topper(marks):
    total_marks = np.sum(marks, axis=1)
    topper_index = np.argmax(total_marks)
    return topper_index, total_marks[topper_index]

topper_index, topper_marks = find_topper(student_marks)
print(f"\nTopper: Student {topper_index + 1} with Total Marks: {topper_marks}")
print(f"Topper's Name: {student_names[topper_index]}")


Topper: Student 7 with Total Marks: 475
Topper's Name: Grace
